#!/usr/bin/env bash
# Usage: Connects to server through script

# Check if the server IP is provided as an argument
if [ -z "$1" ]; then
  echo "Usage: $0 <server_ip>"
  exit 1
fi

# Connect to the server using ssh with the provided private key and user
ssh -i ~/.ssh/school ubuntu@$1
