#!/usr/bin/env bash

# Set the filename and passphrase
KEY_NAME="school"
PASSPHRASE="betty"
KEY_BITS=4096

# Generate the RSA key pair
ssh-keygen -t rsa -b $KEY_BITS -f ~/.ssh/$KEY_NAME -N $PASSPHRASE

